---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: podinfo-secret
  namespace: production
spec:
  encryptedData:
    API_KEY: AgCtaB6gMJvSnTbt1kLTtq/s2v/jXJxn8gh3CxKrUufXzWf4WLoE+kKpNJRFcj4PFN768G0u0oMLdRlkLPZlGQqFtQiGwxdM+pimj/OVl1wqMBVoPt9s/46cvH+ReI+B5oB4NTs29wTohUEGA4tJlIDK6oG5egEcdMzwAItJyH45BYWJSOvYVDoQj4uyfyc/WNqYYMzsb7UFMEMAjZkXxofMSgMPulo8wMLMGaRJcTmR8euRDeipJrNoUQlgRkiC898lKrs83tetplGnKbfnDpB9BD93C+W43xkYicvamRVdAUU0cIxQ5jjxzbC4HYu7uKI6B88t4vkuWA6iiTqwiJiyu9bVYv/gdTBBRsNLVNu+ns94LkRJWv/ZTFTecIwvZMYft2ZAJhuupathoVZ0s7HAaaMk0RUquhWPk44V3GYTPyLDf0ltrpn80wObQ4RVHyIsUhsGfSQldk8vpBh2KVqPekuDY5xtBzWHhCRyRkIJzohGbG/URxO26KDdKGDk8ygkFM885G081OsT+Dm++sk3CxVSNmtuSAnrcfwatbOoA79iVE5dPut9rvKfC9IXhs5RaIULT52uQXDs/sFszdLtT3SH6F0qRKvPNwyRcK1JqDiQOBjI0lz0cIAkukmvHJtKp30CWnaIRZqJCVAi019IqpCqL8S8LCgQl7rFy/7RosP3Yi0+V0a93T6MyXDTUv64kSUieogIoZ8BiImqsCbOkF3Qk+s6xa8=
  template:
    metadata:
      creationTimestamp: null
      name: podinfo-secret
      namespace: production
